// import './globals.css'

'use client';
import "../styles/global.css";
import { Inter } from "next/font/google";
import { QueryClient, QueryClientProvider, Hydrate } from "react-query";

const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient();


export const metadata = {
  title: "OPEN AI ",
  description: "Generated by _NITIN_",
};

//Query client is central hub
//handle all the queries and mutation in your application
//and provide the unified interface to interact with them
//manages and caching data fetching

export default function RootLayout({ children }) {
  return (
    <QueryClientProvider client = {queryClient}>

    {/* Hydrate render components more faster  */}
      {/* <Hydrate state={pageProps.dehydratedState}> */}
      <Hydrate>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
      </Hydrate>
    </QueryClientProvider>
  );
}
